/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * Run the built-in grammar checks (duplicated words, stray whitespace,
 * sentence-start capitalization) over `text`.
 */
export declare function checkGrammar(text: string): Array<GrammarFindingJs>

/**
 * Compute readability metrics (FKGL, Gunning Fog, SMOG, ARI, Coleman-Liau,
 * Flesch ease, Dale-Chall) for `text`.
 */
export declare function computeReadability(text: string): ReadabilityResultJs

export interface GradeLevelsJs {
  fkgl: string
  gunningFog: string
  ari: string
  colemanLiau: string
  fleschEase: string
  daleChall: string
}

export interface GrammarFindingJs {
  kind: string
  utf16Start: number
  utf16End: number
  message: string
  replacements: Array<string>
}

/**
 * List the names of the built-in narrative structure templates
 * (three_act, heros_journey, save_the_cat, kishotenketsu, nonlinear).
 */
export declare function listStructureTemplates(): Array<string>

export interface ReadabilityResultJs {
  fkgl: number
  gunningFog: number
  smog: number
  ari: number
  colemanLiau: number
  fleschEase: number
  daleChall: number
  sentenceCount: number
  wordCount: number
  syllableCount: number
  charCount: number
  polysyllableCount: number
  gradeLevels: GradeLevelsJs
  readabilityVariance: number
}
