/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * Aggregate pacing metrics across all scenes. Returns `null` when
 * `scene_metrics` is empty.
 */
export declare function aggregatePacing(sceneMetrics: Array<PacingMetricsInput>): any

/**
 * Build a causal graph over scenes and analyze plot coherence, counterfactuals,
 * and plot holes.
 */
export declare function analyzeCausality(scenes: Array<string>, characters: Array<string>): any

/** Build voice profiles for every character and flag same-sounding pairs. */
export declare function analyzeCharacterVoices(characterNames: Array<string>, characterDialogueLines: Array<Array<string>>): any

/** Analyze dialogue patterns across all extracted dialogue lines. */
export declare function analyzeDialoguePatterns(allDialogue: Array<DialogueLineInput>, knownCharacters: Array<string>): any

/**
 * Analyze dialogue realism: voice fingerprints, info dumps, formality
 * issues, identical-voice pairs, and power dynamics between characters.
 */
export declare function analyzeDialogueRealism(turnScenes: Array<number>, turnSpeakers: Array<string>, turnTexts: Array<string>, characters: Array<string>): any

/** Analyze foreshadowing setup-payoff arcs across scenes. */
export declare function analyzeForeshadowing(scenesTokens: Array<Array<string>>, totalScenes: number): any

/**
 * Analyze narrative gaps based on signals from other analysis modules: broken
 * promises `(description, promiseScene)`, consequenceless decisions
 * `(character, scene)`, pacing stall zones `(startScene, endScene)`, and
 * unresolved ironies `(description, scene)`.
 */
export declare function analyzeGaps(brokenPromises: Array<[string, number]>, consequencelessDecisions: Array<[string, number]>, stallZones: Array<[number, number]>, unresolvedIronies: Array<[string, number]>, totalScenes: number, climaxScene: number): any

/** Analyze the opening pages of a manuscript for hook strength and agent appeal. */
export declare function analyzeOpening(text: string, genre: string, fullManuscriptVoiceFingerprint?: Array<number> | undefined | null): any

/** Analyze a single scene and return its pacing metrics. */
export declare function analyzePacing(sceneId: number, dialogueTokens: number, totalTokens: number, sentencesCount: number): any

/** Analyze how detected themes evolve and resolve across the manuscript. */
export declare function analyzeResolution(sceneThemes: Array<Record<string, number>>): any

/**
 * Analyze a scene's tokens for anachronistic words given a target historical year.
 * Returns empty if target_year is 0 (no target set).
 */
export declare function analyzeScene(tokens: Array<string>, targetYear: number, sceneId: number): any

/**
 * Analyze information density of a scene's text. `seen_nouns` carries nouns
 * seen in prior scenes across calls (JS has no mutable-reference channel, so
 * the updated set is returned alongside the density result instead of
 * mutated in place).
 */
export declare function analyzeSceneInfoDensity(sceneText: string, seenNouns: Array<string>): any

/**
 * Analyze subtext across scenes (currently a reserved-for-reasoner stub:
 * always returns empty instances with zero density).
 */
export declare function analyzeSubtext(scenes: Array<string>, dialogueSegmentScenes: Array<number>, dialogueSegmentSpeakers: Array<string>, dialogueSegmentQuotes: Array<string>, dialogueSegmentContexts: Array<string>, emotionalStateCharacters: Array<string>, emotionalStateScenes: Array<number>, emotionalStateEmotions: Array<string>, genre: string): any

/** Analyze syntax tension in scene text using the fallback (regex-only) path. */
export declare function analyzeSyntaxTension(sceneText: string): any

/**
 * Scan multiple scenes to infer a gender ("male"/"female"/"unknown") for each
 * named character, from pronoun proximity.
 */
export declare function buildCharacterGenderMap(scenes: Array<string>, characters: Array<string>): any

/**
 * Build the reader's evolving mental model (belief trajectory, dramatic
 * ironies, revelations/twists) across scenes.
 */
export declare function buildMentalModel(scenes: Array<string>, characters: Array<string>, povCharacters: Array<string>, themeKeywords: Array<string>): any

/** Build the promise-payoff ledger from analysis data. */
export declare function buildPromisePayoffLedger(scenes: Array<string>, sceneWordCounts: Array<number>, genre: string, foreshadowingItems: Array<[string, number, boolean]>, characterFirstAppearances: Array<[string, number]>, structureTemplate: string, totalScenes: number): any

/**
 * Build the timeline projection: the given `(documentId, text)` documents, in
 * the order supplied, each tagged with its first detected time hint.
 */
export declare function buildTimeline(documents: Array<[string, string]>): any

/** Build a character's voice profile from their dialogue lines. */
export declare function buildVoiceProfile(characterName: string, dialogueLines: Array<string>): any

export interface CharacterVoiceProfileInput {
  character: string
  avgSentenceLength: number
  vocabularyRichness: number
  questionRate: number
  exclamationRate: number
  contractionRate: number
  formalityScore: number
  avgWordLength: number
  uniquePhrases: Array<string>
  topWords: Array<string>
}

/** Check a manuscript's compliance with genre conventions. */
export declare function checkGenreCompliance(genre: string, hasHea: boolean, hasSolution: boolean, hasTickingClock: boolean, protagonistSurvives: boolean, characterGrowth: boolean, worldbuildingPresent: boolean, wordCount: number, structureHealth: number, tensionArcShape: string): any

/**
 * Run the built-in grammar checks (duplicated words, stray whitespace,
 * sentence-start capitalization) over `text`.
 */
export declare function checkGrammar(text: string): Array<GrammarFindingJs>

/**
 * Collect prose quality issues from scenes: overlong sentences, passive
 * voice, adverb clusters, repetitive openers, cliches, floating-head
 * dialogue, filter words, monotonous rhythm, and purple prose.
 */
export declare function collectProseExamples(scenes: Array<string>): any

/**
 * Pairwise-compare voice profiles and flag characters whose voices are too
 * similar.
 */
export declare function compareVoices(profiles: Array<CharacterVoiceProfileInput>): any

/**
 * Compute confidence for a specific finding based on signal agreement and
 * scene confidence.
 */
export declare function computeFindingConfidence(signalCount: number, totalSignals: number, sceneConfidence: number): number

/** Compute narrative entropy (information-pacing) across the manuscript. */
export declare function computeNarrativeEntropy(scenes: Array<string>, themes: Array<[string, number]>, structureTemplate: string, genre: string, characterArcs: Array<[string, string]>): any

/**
 * Compute readability metrics (FKGL, Gunning Fog, SMOG, ARI, Coleman-Liau,
 * Flesch ease, Dale-Chall) for `text`.
 */
export declare function computeReadability(text: string): ReadabilityResultJs

/** Compute confidence for readability metrics based on sample size. */
export declare function computeReadabilityConfidence(wordCount: number, sentenceCount: number): any

/** Compute confidence for analysis of a scene based on its text content. */
export declare function computeSceneConfidence(sceneText: string, sceneId: number): any

/**
 * Detect genre using SBERT cosine similarity against genre descriptions when the
 * model is available, degrading to the keyword/prose-stats heuristic otherwise.
 */
export declare function detectGenre(themes: Array<string>, tensionPattern: Array<number>, dialogueRatio: number, fkgl: number): any

/**
 * Detect genre from a raw manuscript sample using SBERT cosine similarity when
 * available, falling back to the label/theme-driven `detectGenre` otherwise.
 */
export declare function detectGenreSmart(sampleText: string, themes: Array<string>, tensionPattern: Array<number>, dialogueRatio: number, fkgl: number): any

/** Detect themes using SBERT if available, falling back to keyword detection. */
export declare function detectThemesSmart(scenes: Array<string>, scenesTokens: Array<Array<string>>): any

export interface DialogueLineInput {
  sceneId: number
  quote: string
  speaker: string
  confidence: number
  method: string
  tagVerb?: string
}

/** Evaluate manuscript metrics against a genre's expected quantitative profile. */
export declare function evaluateAgainstGenre(genreLabel: string, fkgl: number, velocity: number, dialogueRatio: number, tensionVariance: number, tonalWhiplashCount: number, wordCount: number): any

/** Explain a pacing issue (long sentences, or a talking-head scene) for one scene. */
export declare function explainPacing(velocity: number, sceneId: number, isTalkingHead: boolean, dialogueRatio: number): any

/**
 * Explain a readability score against a genre's target grade-level range, if
 * it falls outside that range.
 */
export declare function explainReadability(fkgl: number, targetMin: number, targetMax: number, genre: string): any

/**
 * Explain a show-don't-tell issue (`narrative_distance`, `filter_word`,
 * `diluted_action`, or any other issue type) found in `snippet`.
 */
export declare function explainShowDontTell(issueType: string, snippet: string): any

/**
 * Explain a tension issue: a flat run, a sharp drop, or a manuscript with no
 * significant tension peak.
 */
export declare function explainTension(tension: number, prevTension: number, sceneId: number, flatCount: number, flatStart: number, totalScenes: number, maxTension: number): any

/** Explain a tonal shift between two scenes, if `from_tone` and `to_tone` differ. */
export declare function explainToneShift(fromTone: string, toTone: string, sceneId: number, genre: string): any

/**
 * Explain a "white room" issue: a scene with too little sensory grounding
 * for its length.
 */
export declare function explainWhiteRoom(sceneId: number, sensoryCount: number, wordCount: number): any

/** Extract dialogue from a scene and attribute each quote to a speaker. */
export declare function extractDialogue(sceneText: string, sceneId: number, knownCharacters: Array<string>): any

/** Map a writer-declared genre label to a canonical genre, if recognized. */
export declare function genreFromLabel(label: string): any

/** Get the expected quantitative profile for a genre, by label. */
export declare function getGenreProfile(genreLabel: string): any

/** Look up a built-in narrative structure template by name. */
export declare function getStructureTemplate(name: string): any

/** Compute aggregate tension metrics from per-scene suspense scores. */
export declare function getTensionMetrics(sceneScores: Array<number>): any

export interface GradeLevelsJs {
  fkgl: string
  gunningFog: string
  ari: string
  colemanLiau: string
  fleschEase: string
  daleChall: string
}

export interface GrammarFindingJs {
  kind: string
  utf16Start: number
  utf16End: number
  message: string
  replacements: Array<string>
}

/**
 * List the names of the built-in narrative structure templates
 * (three_act, heros_journey, save_the_cat, kishotenketsu, nonlinear).
 */
export declare function listStructureTemplates(): Array<string>

/**
 * Measure how far a `current` (revised) voice profile has drifted from a
 * `baseline` (established) profile across the features both expose.
 */
export declare function measureVoiceDrift(baseline: CharacterVoiceProfileInput, current: CharacterVoiceProfileInput): any

/**
 * Convenience: build both profiles from baseline-text and current-text
 * lines (same speaker/narrator label) and measure drift between them.
 */
export declare function measureVoiceDriftFromText(label: string, baselineLines: Array<string>, currentLines: Array<string>): any

export interface PacingMetricsInput {
  sceneId: number
  dialogueRatio: number
  isTalkingHead: boolean
  velocity: number
  wordCount: number
  entityDensity: number
  nounDensity: number
  informationNovelty: number
  actionDensity: number
}

export interface ReadabilityResultJs {
  fkgl: number
  gunningFog: number
  smog: number
  ari: number
  colemanLiau: number
  fleschEase: number
  daleChall: number
  sentenceCount: number
  wordCount: number
  syllableCount: number
  charCount: number
  polysyllableCount: number
  gradeLevels: GradeLevelsJs
  readabilityVariance: number
}

/**
 * Combine ranked id lists (best first) with reciprocal rank fusion. Returns
 * the fused ranking, strongest first, truncated to `limit`, as
 * `[id, score]` pairs.
 */
export declare function reciprocalRankFusion(rankings: Array<Array<string>>, k: number, limit: number): any

/**
 * Resolve pronoun references to character names within a scene. `gender_map`
 * (character name -> "male"/"female"/"unknown") is inferred from `scene_text`
 * alone when omitted.
 */
export declare function resolveCoreferences(sceneText: string, knownCharacters: Array<string>, genderMap?: Record<string, string> | undefined | null): any

/**
 * Resolve name mentions (surface, context-embedding pairs) into canonical
 * entities of the given `kind` ("character", "setting", "symbol", or "other").
 */
export declare function resolveEntities(mentions: Array<[string, Array<number>]>, kind: string): any

/**
 * Resolve mentions, then apply the writer's persisted corrections (each a JSON
 * object shaped like `EntityCorrection`, e.g. `{"surface": "...", "action":
 * {"kind": "assign", "canonical": "..."}}` or `{"kind": "reject"}`) over the
 * automatic result.
 */
export declare function resolveEntitiesWithCorrections(mentions: Array<[string, Array<number>]>, kind: string, corrections: Array<any>): any

/** Suggest the best-fitting structure template for a set of scene tensions/purposes. */
export declare function suggestBestTemplate(sceneTensions: Array<number>, scenePurposes: Array<string>): any

/**
 * Track per-character and reader epistemic states across scenes, computing
 * asymmetries, revelations, and the suspense curve.
 */
export declare function trackEpistemics(scenes: Array<string>, characters: Array<string>, povCharacters: Array<string>): any

/** Track the thematic argument across the manuscript. */
export declare function trackThematicArgument(scenes: Array<string>, themes: Array<[string, number]>, characters: Array<string>, characterDecisions: Array<[string, number, string]>, genre: string): any

/**
 * Analyze scenes and characters to produce a full world state analysis
 * (facts, continuity violations, character knowledge, information flow).
 */
export declare function trackWorldState(scenes: Array<string>, characters: Array<string>): any

/**
 * Train a corpus embedding from `texts` (default build options) and return
 * the `k` vocabulary words most similar to `word`, strongest first.
 *
 * Combined rather than exposing `CorpusEmbedding` as a stateful object: napi
 * cannot cheaply hold a live Rust struct across separate calls without
 * `#[napi]` on the struct itself (a bigger design decision than this binding
 * pass), so training and querying are fused into one call instead.
 */
export declare function trainAndFindNearest(texts: Array<string>, word: string, k: number): any

/**
 * Train a corpus embedding from `texts` (default build options) and return
 * the cosine similarity between `word_a` and `word_b` in that space.
 *
 * Same fused-call design as `trainAndFindNearest`, avoiding a stateful
 * `CorpusEmbedding` handle across the FFI boundary.
 */
export declare function trainAndSimilarity(texts: Array<string>, wordA: string, wordB: string): number

/** Score how well a set of scene tensions/purposes matches a structure template. */
export declare function validateStructure(templateName: string, sceneTensions: Array<number>, scenePurposes: Array<string>): any

/**
 * Rank the most-frequent content words in `text`, most-frequent first,
 * keeping at most `limit`, using the crate's built-in stopword set.
 */
export declare function wordFrequencies(text: string, limit: number): any

/**
 * Count and rank already-tokenized `words`, applying the same content-word
 * filter, ordering, and `limit` as `wordFrequencies`, using the crate's
 * built-in stopword set.
 */
export declare function wordFrequenciesFromWords(words: Array<string>, limit: number): any
